### ISSUE TITLE
Error: Failed to install 'fastTopics' from GitHub:  installation of package ‘RcppArmadillo’ had non-zero exit status

### ISSUE THREAD

**Issue by jhsiao999** [stephenslab/fastTopics#1]
Hi @pcarbo,

I received an error while installing fastTopics. Please see the end of this message for the session information. Any suggestions?

Thanks,
Joyce

> devtools::install_github("stephenslab/fastTopics")
> library(fastTopics)

Downloading GitHub repo stephenslab/fastTopics@master

> dplyr        (0.8.4 -> 0.8.5      ) [CRAN]
> RcppParallel (4.4.4 -> 5.0.0      ) [CRAN]
> RcppArmad... (NA    -> 0.9.870.2.0) [CRAN]
> purrr        (0.3.3 -> 0.3.4      ) [CRAN]

Installing 4 packages: dplyr, RcppParallel, RcppArmadillo, purrr

Error: Failed to install 'fastTopics' from GitHub:
  (converted from warning) installation of package ‘RcppArmadillo’ had non-zero exit status
Traceback:

1. devtools::install_github("stephenslab/fastTopics")
2. pkgbuild::with_build_tools({
 .     ellipsis::check_dots_used(action = getOption("devtools.ellipsis_action", 
 .         rlang::warn))
 .     {
 .         remotes <- lapply(repo, github_remote, ref = ref, subdir = subdir, 
 .             auth_token = auth_token, host = host)
 .         install_remotes(remotes, auth_token = auth_token, host = host, 
 .             dependencies = dependencies, upgrade = upgrade, force = force, 
 .             quiet = quiet, build = build, build_opts = build_opts, 
 .             build_manual = build_manual, build_vignettes = build_vignettes, 
 .             repos = repos, type = type, ...)
 .     }
 . }, required = FALSE)
3. install_remotes(remotes, auth_token = auth_token, host = host, 
 .     dependencies = dependencies, upgrade = upgrade, force = force, 
 .     quiet = quiet, build = build, build_opts = build_opts, build_manual = build_manual, 
 .     build_vignettes = build_vignettes, repos = repos, type = type, 
 .     ...)
4. tryCatch(res[[i]] <- install_remote(remotes[[i]], ...), error = function(e) {
 .     stop(remote_install_error(remotes[[i]], e))
 . })
5. tryCatchList(expr, classes, parentenv, handlers)
6. tryCatchOne(expr, names, parentenv, handlers[[1L]])
7. value[[3L]](cond)

> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS/LAPACK: /opt/conda/lib/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6      pillar_1.4.3      compiler_3.6.1    prettyunits_1.1.1
 [5] base64enc_0.1-3   remotes_2.1.1     tools_3.6.1       testthat_2.3.2   
 [9] digest_0.6.25     pkgbuild_1.0.7    uuid_0.1-2        pkgload_1.0.2    
[13] jsonlite_1.6.1    evaluate_0.14     memoise_1.1.0     rlang_0.4.5      
[17] IRdisplay_0.7.0   cli_2.0.2         curl_4.3          IRkernel_1.1     
[21] repr_1.1.0        withr_2.2.0       desc_1.2.0        fs_1.3.1         
[25] devtools_2.2.1    rprojroot_1.3-2   glue_1.4.0        R6_2.4.1         
[29] processx_3.4.2    fansi_0.4.1       sessioninfo_1.1.1 pbdZMQ_0.3-3     
[33] callr_3.4.3       magrittr_1.5      backports_1.1.6   ps_1.3.2         
[37] ellipsis_0.3.0    htmltools_0.4.0   usethis_1.5.1     assertthat_0.2.1 
[41] crayon_1.3.4

**Comment by pcarbo** [comment]
@jhsiao999 What happens when you run

```R
install.packages("Rcpp")
install.packages("RcppArmadillo")
```

Do you get an error when installing either of these packages? If so, please share the error message.

**Comment by jhsiao999** [comment]
Hi @pcarbo,

I was able to install `Rcpp` but not `RcppArmadillo'. Here's my warning message:

```
Warning message in install.packages("RcppArmadillo"):
“installation of package ‘RcppArmadillo’ had non-zero exit status”
Updating HTML index of packages in '.Library'

Making 'packages.html' ...
done
```

I check my gcc version. It's 7.3.0.

```
$gcc --version
gcc (crosstool-NG 1.23.0.449-a04d0) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by pcarbo** [comment]
@jhsiao999 That error message is not terribly informative. Nonetheless, it seems that you are having an issue installing RcppArmadillo for reasons that are not clear. I suggest the following. Download the source [here](https://github.com/RcppCore/RcppArmadillo). Run

```
R CMD build RcppArmadillo
R CMD INSTALL RcppArmadillo_0.9.870.2.0.tar.gz
```

and hopefully that will give you a more informative error message if it fails.

**Comment by jhsiao999** [comment]
@pcarbo Thanks for the help. I ended up cloning the RcppArmadillo repository and installing using devtools::install(). I had some issues installing from the source but not sure why... 

I am running fastTopics now. Thanks!

**Comment by pcarbo** [comment]
Great!
