### ISSUE TITLE
Naming in a structure_plot  for small number of samples

### ISSUE THREAD

**Issue by maxybck** [stephenslab/fastTopics#10]
I am trying to do create a fast_topics_model for a small number of samples (12) into four groups, but when I try to create a structure_plot I can't add names through the grouping option. I can get the structure plot to work when I don't try and name/group the samples, but it won't work if I try and add the grouping option. It is entirely possible that this simply isn't possible with a small number of samples. If it is not possible to plot this way, is there an alternative method where I could create a plot of the structure with names? Also if I have your attention, how do I extract the top genes for each topic?

![image](https://user-images.githubusercontent.com/57376252/112389267-16d81e00-8cba-11eb-9156-cffc2c4be6ce.png)

![image](https://user-images.githubusercontent.com/57376252/112389476-661e4e80-8cba-11eb-87c4-2ca53a40233e.png)

plotting without grouping:

![image](https://user-images.githubusercontent.com/57376252/112389770-e80e7780-8cba-11eb-9723-23cccc241e37.png)

attempted plotting with grouping:
![image](https://user-images.githubusercontent.com/57376252/112389678-c1504100-8cba-11eb-92cd-531b199fd1c1.png)

**Comment by pcarbo** [comment]
@maxybck I'm not sure if topic modeling will work well for a data set with n = 12. If it does work, I expect that you wouldn't be able to go beyond k = 2 or k = 3 topics. In any case, you might find that `pca_plot` works better for you than `structure_plot`.

**Comment by maxybck** [comment]
Hi

How many samples would be enough? I was thinking of mining some exciting samples from similar tissues and including our data. Would 50 samples work? I'm just trying to geta sense of when this might be useful and how to make it useful.

Best
Max

written from my phone pardon any misspelling

________________________________

**Comment by pcarbo** [comment]
What is "enough" will depend on many factors, including the complexity of the structure in the data, the amount of noise in the measurements, etc. For expression data sets, we apply these methods to data sets with hundreds or thousands of samples, but you may be able to get away with fewer samples for simpler analyses (e.g., with a small number of topics).

**Comment by pcarbo** [comment]
@maxybck Just an FYI that the new plotting interface should better accommodate your data. (And if you have additional issues, I would welcome feedback.)

**Comment by maxybck** [comment]
Thank you for the update! I will take a peak at this later today.
