### ISSUE TITLE
Imported Count Matrix by Seurat, but Col Names are Cell Names

### ISSUE THREAD

**Issue by h1hui** [stephenslab/fastTopics#13]
I imported raw count matrix from my seurat object, using function 
`counts <- GetAssayData(object,"counts")`
And then found out my column names are cell names, unlike the sample dataset. How should I continue fastTopics from my Seurat object?

**Comment by pcarbo** [comment]
@h1hui, Yes you should do 

```r
counts <- t(GetAssayData(object,"counts"))
```

See also the fastTopics Seurat wrapper, which you can find [here](https://github.com/stephenslab/seurat-wrappers).

**Comment by h1hui** [comment]
Thanks! It solved.
