### ISSUE TITLE
Extracting all the genes for a given topic AND how to change volcano plot

### ISSUE THREAD

**Issue by maxybck** [stephenslab/fastTopics#17]
firstly, You briefly mentioned this was possible in another thread, but I was hoping to get a little more clarification for how to extract the genes that are important for any single topic. I have a nice plot shown below, but I was wondering how to get a systematic list of the genes in the top right as you mention in your vignette. Secondly, can you point me in the direction of how to change dot size and/or font color etc. for the volcano plots. Thank you for your help in advance!

To make this plot I call 

volcano_plot(dfa_out3,k=1,label_above_quantile = 0.995)

![image](https://user-images.githubusercontent.com/57376252/125011359-88e43100-e025-11eb-958d-443cb91afd9e.png)

**Comment by pcarbo** [comment]
@maxybck We are making some significant improvements to the differential expression analysis so I will leave this issue open and update you when these improvements are completed.

Typically the most relevant ("driving") genes are found toward the top-left corner of the volcano plot (high LFC, strong support); it is unclear if a single ranking method will work well generally.

For customizing the volcano plot you would modify the `ggplot_call` argument to `volcano_plot`. The default setting is `volcano_plot_ggplot_call`. If you run `print(volcano_plot_ggplot_call)` this will give you the code which you can of course adapt. Hope that helps.

**Comment by pcarbo** [comment]
@maxybck Just so you know we have made improvements to the differential expression analysis and you can see the [vignette](https://stephenslab.github.io/fastTopics/articles/single_cell_rnaseq_basic.html) for an illustration of how it works.
