### ISSUE TITLE
RcppParallel library flags

### ISSUE THREAD

**Issue by YPARK** [stephenslab/fastTopics#21]
It took me a while until I found out that`RcppParallel::RcppParallelLibs()` generates nothing on my Mac OS laptop. This gave me errors in installation and loading. 

After I set the following in `.R/Makevar`, I had no issues.

```
TBB = /usr/local/opt/tbb/
TBB_INC = /usr/local/opt/tbb/include
TBB_LIB = /usr/local/opt/tbb/lib
```

**Comment by pcarbo** [comment]
@YPARK Thanks for this. Did you install `RcppParallel` from source? My understanding is that if you install `RcppParallel` using `install.packages` then the TBB libraries will be included in the installation, so you don't need to install TBB separately (I may be wrong though).

**Comment by YPARK** [comment]
@pcarbo I think it's a Mac-related issue. When I first installed `RcppParallel` binary, it didn't check TBB and assumed that was installed. For the record, I am using `R` and `tbb` installed by `homebrew` and `RcppParallel` with `type="source"`.

**Comment by pcarbo** [comment]
I'm going to close this issue but thanks for sharing this info.
