### ISSUE TITLE
structure_plot not working on "fit" from "predict()" function

### ISSUE THREAD

**Issue by Zepeng-Mu** [stephenslab/fastTopics#22]
Hello,
I'm following the steps in the vignette to first predict topics in other groups of cells and then plot the structure plot, but I got this error in the latest version of fastTopics: "Error in value[[3L]](cond) : Invalid selection of loadings".

This is because `select_loadings` tries to subset `Ln` in the `fit_test` from `predict`, which does not have the same row numbers as `fit_test$L` in this case.

Thanks so much!

**Comment by Zepeng-Mu** [comment]
Hi, I'm using version 0.6-97. In my case I first fit the model on 5000 cells, and then use this to predict another 30000 cells. So many cells in "fit_test" does not appear in the original "fit".

In the "single_cell_rnaseq_basic" vignette the cells in "count_test" seems to be a subset of those in "count", so in the vignette there is no error.

I wonder if I can just manually set Ly and Ln to L, since they are going to be the same without extrapolate?

Thanks!

**Comment by pcarbo** [comment]
`counts_test` is not a subset of `counts`:

```
> intersect(rownames(counts),rownames(counts_test))
0
```

You should be able to run `predict` on a separate set of cells so long as the genes (or more generally, columns of the counts matrix) are same.

If you can send me a code snippet I can run I can troubleshoot your problem.

**Comment by pcarbo** [comment]
The problem is not fastTopics, rather the code I used in the vignette. Here is some better code:

```R
Ltest <- predict(fit,counts_test)
fit_test <- init_poisson_nmf(X = counts_test,L = Ltest,init.method = "random")
```

Does it work for you now?

**Comment by Zepeng-Mu** [comment]
Let me try this on my data. Thanks!
