### ISSUE TITLE
Feature request: Gamma prior for NMF loadings

### ISSUE THREAD

**Issue by jackkamm** [stephenslab/fastTopics#27]
I'd like to request an option to incorporate a Gamma prior for the NMF loadings into the Poisson-NMF likelihood function.

I believe this would make the fastTopics model equivalent to the original Latent Dirichlet Allocation, due to the close relationship between Gamma and Dirichlet distributions (in particular, independent Gammas with shared scale parameter, become Dirichlet after dividing by their sum; e.g., https://en.wikipedia.org/wiki/Dirichlet_distribution#Gamma_distribution).

Practically, I think this would allow fastTopics to encourage sparsity, by setting the Gamma/Dirichlet shape parameter <1 -- this is my main motivation for wanting this feature.

I may be interested to help with a PR, but before I try this, would like to know your opinion on how difficult this would be to implement, and whether you already considered something like this.

**Comment by jackkamm** [comment]
I just took a second look at your paper and saw that you already considered using Gamma priors in Appendix A2 -- sorry, I should have checked that before posting.

However, I don't see a way to set any Gamma prior parameters in fit_topic_model() -- is it possible to specify these?

**Comment by pcarbo** [comment]
@jackkamm Yes in the paper we mention Dirichlet priors on F in the topic model (i.e., the word frequencies matrix). Are you interested in encouraging sparse word frequencies F, or sparse topic proportions L (or both)? Note that Gamma priors on L in Poisson NMF and Dirichlet priors on L in the (multinomial) topic model are not equivalent. You only get the equivalence for F.

**Comment by pcarbo** [comment]
Unfortunately, *maximum a posteriori* (MAP) estimation with a Dirichlet prior [is a hard problem](https://proceedings.neurips.cc/paper/2011/hash/3871bd64012152bfb53fdf04b401193f-Abstract.html), which is one reason, I believe, why the variational inference approach implemented in LDA is more doable than MAP estimation.

**Comment by pcarbo** [comment]
I don't recall the exact priors used, but you might check out the [maptpx](https://github.com/TaddyLab/maptpx) R package.

**Comment by jackkamm** [comment]
Thanks for the references, I will check them out.

I'll close out this feature request, since its scope seems larger than I had initially thought.
