### ISSUE TITLE
bug in compile_structure_plot_data when a group is empty

### ISSUE THREAD

**Issue by willwerscheid** [stephenslab/fastTopics#28]
A group can be empty after downsampling. In this case n = 0, so the line `dat <- data.frame(sample = rep(1:n, times = k), topic = rep(topics, 
    each = n), prop = c(L[, topics]))` produces an error (1:n is the vector c(1, 0), so sample has length 2k, but topic has length 0)

**Comment by pcarbo** [comment]
@willwerscheid What would you suggest? One option would be to avoid removing all samples in a group; e.g., set a minimum number of samples per group.

**Comment by willwerscheid** [comment]
I'm not sure -- would just returning an empty data frame if n = 0 work there? or do you end up with overlapping labels? if the latter then it probably makes more sense to remove the groups
