### ISSUE TITLE
Update Vignette

### ISSUE THREAD

**Issue by nikofleischer** [stephenslab/fastTopics#29]
In the vignette, the function `diff_count_clusters` and `diff_count_analysis` are called to calculate differences in gene contribution to the topics. these don't exist in the package anymore. 

After some confusion I deducted that `de_analysis()` is the correct function name now, might be good to update. 

Best and thanks for the great package,
Niko 

EDIT: there are more changes, I will update everything I find here :) 

1) parameters for `volcano_plot` changed. `label_above_quantile` replaced by `do.quantile`

**Comment by pcarbo** [comment]
Thanks @sparsepix. Yes indeed the vignettes need to be updated since several major changes have been making to the interface. I unfortunately won't be able to address this immediately but I will leave this Issue open as a reminder.

**Comment by pcarbo** [comment]
@nikofleischer I've updated the [vignettes](https://stephenslab.github.io/fastTopics/articles) finally. I apologize for the long delay.
