### ISSUE TITLE
fit_poisson_nmf Error in solve.QP(M, d, A, b0)

### ISSUE THREAD

**Issue by jhsiao999** [stephenslab/fastTopics#3]
@pcarbo 

I encountered the following error message when fitting k >= 15. (tried 15, 16, 17)

The dimension of the data is 7,490 cell by 2,540 genes. 72% of the input count matrix has zero entries.

Thanks,
Joyce

```
Error in solve.QP(M, d, A, b0): matrix D in quadratic function is not positive definite!
Traceback:

1. fit_poisson_nmf(tmp, k = i, init_method = "topicscore", numiter = 100, 
 .     method = "scd", verbose = FALSE, control = list(extrapolate = TRUE))
2. init_poisson_nmf(X, k = k, init_method = init_method, control = control, 
 .     verbose = verbose)
3. topic_score(X, k)
4. vertex_hunting(R, k0, m)
5. simplex_dist(X[j, ], X[B[, i], , drop = FALSE])
6. solve.QP(M, d, A, b0)
7. stop("matrix D in quadratic function is not positive definite!")
```

**Comment by pcarbo** [comment]
It seems like the topic-SCORE initialization still has some rough edges that need to be worked out. @jhsiao999 The simplest workaround, while I investigate this bug, is to run `fit_poisson_nmf` with `init_method = "random"`.

**Comment by pcarbo** [comment]
I'm guessing it it is due to some columns having very low variance.

**Comment by pcarbo** [comment]
@jhsiao999 I made a small change in an attempt to solve your problem. I was unable to reproduce your error, but I think the change I made might help. Can you please reinstall fastTopics and try again?

**Comment by jhsiao999** [comment]
@pcarbo The issue appears to have been solved. I re-installed the package and ran the method on my dataset using K=16 and no issue so far. The dataset has 64,240 cells from 18,854 genes. The previous version generated this error at K=12. Thanks!

**Comment by pcarbo** [comment]
@jhsiao999 Thanks for the update!
