### ISSUE TITLE
Geting Help for FastTopics Error

### ISSUE THREAD

**Issue by geng-lee** [stephenslab/fastTopics#30]
Hi,

How to solve this error, and use FastTopics to process Seurat Object?

How to use FastTopics to process Seurat Object, demonstrating data is not a standard Seurat Object. Although I extracted some of the information in Seurat Object to build a similar list, I still failed to run, and I encountered many errors. E.g: 

structure_plot(fit,colors = topic_colors,topics = 1:16,gap = 25,
+                grouping = samples)
Error in structure_plot(fit, colors = topic_colors, topics = 1:16, gap = 25,  : 
  Input argument "grouping" should be a factor with one entry for each row of fit$L
In addition: Warning message:
In xtfrm.data.frame(x) : cannot xtfrm data frames

Looking forward to your reply！

Best,
Jamie

**Comment by pcarbo** [comment]
@geng-lee It looks like you successfully ran `fit_topic_model` or `fit_poisson_nmf`? Could you share your `fit` output in an .RData or .rds file?

**Comment by geng-lee** [comment]
> @geng-lee看起来你成功地跑了`fit_topic_model`？`fit_poisson_nmf`你能`fit`在 .RData 或 .rds 文件中分享你的输出吗？

OK！Thank you very much!
Could you give me an e-mail address? I will send you the data and code. The .rds file size is huge.

**Comment by geng-lee** [comment]
I have already sent an email to this e-mail address. pcarbone@bsd.uchicago.edu

If you have any questions, please contact me, look forward to your reply！

**Comment by pcarbo** [comment]
I got it, thanks.
