### ISSUE TITLE
function error-diff_count_clusters() & diff_count_analysis()

### ISSUE THREAD

**Issue by geng-lee** [stephenslab/fastTopics#31]
Hi,
 
Can the structure_plot function be displayed with a weight? Too many color blocks make me unable to distinguish their characteristics. 
 
Second, I loaded FastTopics, but I couldn't use the function. I received the following error:
 
```
library(fastTopics)
 
dfc_out <- diff_count_clusters(samples$group,counts)
Error in diff_count_clusters(samples$group, counts) :
  没有"diff_count_clusters"这个函数
dfa_out <- diff_count_analysis(fit_k,counts)
Error in diff_count_analysis(fit_k, counts) :
  没有"diff_count_analysis"这个函数
```

Thanks!
 
Best,
Jamie

**Comment by pcarbo** [comment]
@geng-lee Please use `de_analysis` instead. (Apologies the vignettes need to be updated.)

**Comment by geng-lee** [comment]
OK，Thanks！😁
