### ISSUE TITLE
diff_count_clusters not found

### ISSUE THREAD

**Issue by NicoloPecco** [stephenslab/fastTopics#32]
Hi!

R cannot find the diff_count_clusters functions. It gives me this error: 'could not find function "diff_count_clusters'.

Do you know why?

Thanks in advance,

Nicolo

**Comment by pcarbo** [comment]
Hi @NicoloPecco thanks for your interest in fastTopics. This function has been removed; please use `de_analysis` instead. (Sorry, the vignettes have not been updated accordingly.)

**Comment by NicoloPecco** [comment]
Thanks!

dfa_out <- de_analysis(fit,counts) works. 
Can you please provide the last part of the vignettes for the usage with the de_analysis function?

Thanks,

Nicolo

**Comment by pcarbo** [comment]
Yes, I need to update the vignnette. I'll leave this ticket open as a reminder to do this.

**Comment by pcarbo** [comment]
Thanks for the reminder, Nicolo. It is near the top of my to-do list.

**Comment by pcarbo** [comment]
@NicoloPecco I've updated the [vignettes](https://stephenslab.github.io/fastTopics/articles) finally. I apologize for the long delay.
