### ISSUE TITLE
Curious about how fast is the CD algorithm compared to SQUAREM 

### ISSUE THREAD

**Issue by Zilong-Li** [stephenslab/fastTopics#34]
Hi, 

Thanks for your work. I am from another field.  After reading your paper on the comparison of performance between "CD" and "EM" , I am curious about how fast is the CD algorithm compared to the accelerated EM, eg. [SQUAEM](https://cran.rstudio.com/web/packages/SQUAREM/index.html) package which was proposed by https://onlinelibrary.wiley.com/doi/full/10.1111/j.1467-9469.2007.00585.x

**Comment by pcarbo** [comment]
@Zilong-Li SQUAREM and DAAREM are very nice methods (and R packages) and often work very well, but I found that they did not work well in this setting (perhaps due to the non-negativity constraints). This one reason why we used the extrapolation method of Ng & Gillis.

**Comment by Zilong-Li** [comment]
That makes sense. Thanks 🙏
