### ISSUE TITLE
Type I error control for homogenous case

### ISSUE THREAD

**Issue by william-denault** [stephenslab/fastTopics#42]
Hello Peter,

I am wondering if the Differential analysis has some kind of type I error control.

If I understand correctly, the model estimates a multinomial model and then tests which genes are differentially expressed.
I might a missed something, but do you need to have the number of components, right? Because when I test for DE on a dummy homogeneous model (see below) I find many "genes" that are significantly differentially expressed.

Could you let me know if I am doing something wrong?

`set.seed(1)
tt <- matrix (rpois(lambda=1 , n=1000*50), ncol = 50)
library(fastTopics)
res <- fit_topic_model(tt, k=2)
plot(res)
de <- de_analysis(res ,tt,pseudocount = 0.1 )
summary(de
        )
 
library(cowplot)
plot_progress(res,x = "iter",add.point.every = 10,colors = "black") +
  theme_cowplot(font_size = 10)
volcano_plot(de,k = 1)
`

**Comment by pcarbo** [comment]
@william-denault The `de_analysis` treats the membership matrix (L) as "known", so if this is completely wrong (say, hallucinates two clusters/topics, as in your example), then `de_analysis` will also give results that don't make any sense.
So yes one needs to use this tool appropriately.

Perhaps this could be addressed by estimating uncertainty in L, but this is a difficult problem.

**Comment by william-denault** [comment]
@pcarbo thank you for the quick feedback.

This makes sens. Thank you for clarifying this point
