### ISSUE TITLE
Considerations for bulk RNAseq

### ISSUE THREAD

**Issue by kayserb** [stephenslab/fastTopics#47]
Thanks for the great package and clear documentation. It's been a really insightful tool to use!

I would like to apply it to bulk RNAseq data. Are there any considerations regarding data processing or parameter values to set when running on bulk (as compared to single cell). Or maybe something like GeoMx spatial data that is very "bulk like" in terms of many cells per region of interest. Two things in particular:

1) Is the greater overdispersion of bulk RNAseq compared to scRNAseq an issue?
2) I wouldn't apply it to very small RNAseq experiments, but perhaps 50-200 samples and anywhere from 2000 to 15000 genes depending on how much filtering should be applied to help the processing time.

I appreciate any insight you may have.

**Comment by pcarbo** [comment]
Hi @kayserb thanks for your questions. Indeed while we have focussed on single-cell data, fastTopics can also be applied to bulk data, and in fact we have done so in [this paper](https://doi.org/10.1038/s41590-023-01722-8). [See also [here](https://github.com/pcarbo/lps) for details.] These data sets were roughly of the same size as yours.

The question of overdispersion remains an unresolved one; it is possible that models other than the Poisson would yield better (less noisy) "topics". A bigger issue in our experiennce has been the presence of batch effects. When these effects are non-negligiblee, this could lead to mis-estimation of the topics. We have an example of this in the _Genome Biology_ paper.

Hope that helps.

**Comment by kayserb** [comment]
Thanks so much for the insight and references @pcarbo. All looks pretty straightforward for analyzing bulk data. And as a bonus, you've also piqued my interest in using SusieR for gene set enrichment analysis!
