### ISSUE TITLE
Segmentation fault in de_analysis with nc > 1

### ISSUE THREAD

**Issue by aksarkar** [stephenslab/fastTopics#57]
Minimal example:

```r
library(fastTopics)
sessionInfo()
data(pbmc_facs)
out <- de_analysis(pbmc_facs$fit, pbmc_facs$counts, control=list(nc=2, nc.blas=1, nsplit=32))
saveRDS(out, "out.rds")
```

Complete output is [attached](https://github.com/user-attachments/files/18044629/de_analysis.log). The specific error message changes depending on how many cores were requested.

fastTopics f075a01ccb401d91e9a68302f27d401a0a131822

**Comment by pcarbo** [comment]
@aksarkar Could you please tell me which version of RcppArmadillo you have installed?

**Comment by pcarbo** [comment]
@aksarkar I ran this code on a midway3 node with R 4.1.0 and 1 GB of memory, and using the same versions of fastTopics, Rcpp and RcppParallel (and the latest version of RcppArmadillo available from CRAN), and I could not reproduce these errors. So I'm not sure why you are getting these errors with your setup. I'll keep an eye out for this possible bug. If you get any more useful information about this, please let me know.

**Comment by pcarbo** [comment]
@aksarkar OpenBLAS has been updated recently, and RhpcBLASctl has not been updated since 2023. It also appears that RhpcBLASctl is no longer being maintained.

**Comment by aksarkar** [comment]
Setting the environment variable myself explicitly allowed me to work around this. I am not sure of the best way to handle this in the package. Maybe warn if the environment variable isn't set?

**Comment by pcarbo** [comment]
Not all BLAS libraries have multithreading (in fact I would say most people do not install R with a multithreaded BLAS) — so this environment variable doesn't always need to be set. The other complication is that different BLAS libraries use different environment variables.
