### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by l-cli** [stephenslab/fastTopics#6]
I used the command ` remotes::install_github('stephenslab/seurat-wrappers')` to install the wrappers, but the following error occurred:

![image](https://user-images.githubusercontent.com/55997222/106350633-30ea1700-629c-11eb-825e-1b027e940a9a.png)

Is there a reason for this? I tried both updating the packages recommended by the program as well as not updating them, but it seems to make no difference.
Thank you!

**Comment by pcarbo** [comment]
Hi @l-cli. Looks like the issue occurs when installing fastTopics. Can you please run

```r
remotes::install_github("stephenslab/fastTopics")
```

Does it give the same error?

**Comment by pcarbo** [comment]
Also, can you please run `sessionInfo()` in R and send the output so that I have information about your setup?

**Comment by l-cli** [comment]
Looks like installing fastTopics separately mysteriously solved it! Thank you for the help!
