### ISSUE TITLE
Convergence test and input count matrix

### ISSUE THREAD

**Issue by satriaps** [stephenslab/fastTopics#7]
I really like the idea of using NMF as a way to tease out hidden patterns from bulk/sc gene expression data. 
1. It is recommended in the vignette to use raw count matrix as an input to the fit_topic_model function. However, raw count data has been empirically known to have a negative binomial distribution and many different transformations have been suggested to take into account the overdispersion nature of the data. Is there any specific reason to use the raw count data vs using the variance-stabilized transformed data. 
2. NMF optimization problems are ill-posed. The non-uniqueness of the solutions usually required users to run the optimization algorithms many times to get a more stable estimate. Is there any plan to implement a convergence test in fit_poisson_nmf function? It would be nice to have that feature in the function so users don't have to manually inspect the convergence curve when running multiple trials.

**Comment by pcarbo** [comment]
@satriaps Thanks for your interest in fastTopics. To answer your questions:

1. The use of the multinomial measurement model (upon which the topic model is based) is supported by several recent publications, among them [Townes *et al* (2019)](doi.org/10.1186/s13059-019-1861-6) and [Sarkar & Stephens (2020)](https://doi.org/10.1101/2020.04.07.030007). It is  true some accounting of overdispersion could help in some settings. Most importantly, you should use the "raw" counts, not the log-transformed counts.

2. Yes, that is a feature that I would like to implement. Thank you for the suggestion. One thing I should say though is that people do not typically wait for the optimization to "converge" to a fixed point (however convergence is measured), particularly for large or complex data sets. So my general advice is that monitoring convergence of the optimization is helpful, but, depending on the setting, a good solution may not require convergence.

Hope that helps.

**Comment by aksarkar** [comment]
@pcarbo (2) is now addressed by c71461e2689f06659d7e88833f5ce3c5e14e9e3c so this issue can be closed.

**Comment by pcarbo** [comment]
Thanks!
