### ISSUE TITLE
Extract top genes for each topic

### ISSUE THREAD

**Issue by chendianyu** [stephenslab/fastTopics#9]
Hi, I wonder is there any similar function in `fastTopics` to extract top genes for each topic from the result of  `fit_topic_model()` as `ExtractTopFeatures()` in `CountClust`? I have tried to extract genes based on relative expression levels but I got many genes shared in different topics.

**Comment by pcarbo** [comment]
@chendianyu Yes, use `diff_count_analysis`. See also the examples in [the vignette](https://stephenslab.github.io/fastTopics/articles/single_cell_rnaseq_basic.html).
